language: android
android:
  components:
    - tools
    - build-tools-24.0.0
    - extra-android-support
    - extra-android-m2repository
    - android-24
  licenses:
    - 'android-sdk-license-.+'

jdk: oraclejdk8
sudo: false

before_install:
 - chmod +x gradlew

script:
  - ./gradlew clean build
